from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class BehavioralFinding(BaseModel):
    """Structured record of an observed behavioral pattern or investigative lead."""
    detection_id: str = Field(..., description="Deterministic unique identifier for this finding")
    dataset_id: str = Field(..., description="Unique dataset identifier to preserve strict dataset scoping")
    detection_type: str = Field(..., description="Type of behavioral pattern detected")
    entity_type: str = Field(..., description="Target entity type: wallet, transaction, or ip")
    entity_id: str = Field(..., description="Primary identifier of flagged entity (address, txid, or IP)")
    severity_indicator: str = Field(..., description="Prominence or investigative priority: informational, low, medium, high")
    confidence: float = Field(..., description="Technical confidence score in [0.0, 1.0] based on evidence completeness")
    observed_facts: Dict[str, Any] = Field(default_factory=dict, description="Structured quantitative facts observed")
    supporting_transaction_ids: List[str] = Field(default_factory=list, description="Associated Bitcoin transaction IDs")
    supporting_ips: List[str] = Field(default_factory=list, description="Associated IP addresses where available")
    first_seen: Optional[str] = Field(None, description="Earliest ISO-8601 timestamp associated with finding")
    last_seen: Optional[str] = Field(None, description="Latest ISO-8601 timestamp associated with finding")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Configurable threshold parameters applied")
    explanation: str = Field(..., description="Neutral forensic description of what was observed and rule triggered")
    limitations: List[str] = Field(default_factory=list, description="Methodological limitations, caveats, and missing data points")


class DetectorSummary(BaseModel):
    """Status and findings count for an individual behavioral detector."""
    detector_name: str = Field(..., description="Canonical detector name")
    status: str = Field(..., description="Execution status: active, completed, insufficient_temporal_history, insufficient_data")
    findings_count: int = Field(..., description="Number of findings generated by this detector")
    message: Optional[str] = Field(None, description="Operational notes or insufficient-data reasoning")


class BehaviorSummary(BaseModel):
    """High-level summary of behavioral detection results across a dataset."""
    dataset_id: str = Field(..., description="Target dataset ID")
    total_findings: int = Field(..., description="Total count of behavioral findings")
    findings_by_type: Dict[str, int] = Field(default_factory=dict, description="Count of findings keyed by detection type")
    findings_by_severity: Dict[str, int] = Field(default_factory=dict, description="Count of findings keyed by severity indicator")
    entities_flagged_count: int = Field(..., description="Number of distinct entities with one or more findings")
    detector_summaries: List[DetectorSummary] = Field(default_factory=list, description="Per-detector status and metrics")


class BehavioralMetadata(BaseModel):
    """Metadata detailing detector version, configured thresholds, feature definitions, and limitations."""
    dataset_id: str = Field(..., description="Target dataset ID")
    detector_version: str = Field("1.0.0", description="Behavioral detection engine version")
    enabled_detectors: List[str] = Field(default_factory=list, description="List of enabled detector names")
    configurable_thresholds: Dict[str, Any] = Field(default_factory=dict, description="Threshold parameters applied during run")
    feature_definitions: Dict[str, str] = Field(default_factory=dict, description="Descriptions of behavioral metrics evaluated")
    limitations: List[str] = Field(default_factory=list, description="System-level forensic limitations and caveats")
    created_at: str = Field(..., description="UTC ISO-8601 execution timestamp")


class BehavioralDetectionRequest(BaseModel):
    """Configurable parameters for running behavioral detection."""
    min_fan_in_sources: int = Field(2, ge=2, description="Minimum distinct sources to trigger fan-in indicator")
    min_fan_out_destinations: int = Field(2, ge=2, description="Minimum distinct destinations to trigger fan-out indicator")
    rapid_dispersion_window_seconds: int = Field(1800, ge=1, description="Max elapsed seconds for rapid dispersion")
    rapid_dispersion_min_destinations: int = Field(2, ge=2, description="Min destinations for rapid dispersion")
    burst_window_seconds: int = Field(3600, ge=1, description="Sliding window in seconds for burst detection")
    burst_min_tx_count: int = Field(3, ge=2, description="Min transaction count within window to trigger burst")
    dormancy_threshold_seconds: int = Field(86400 * 30, ge=86400, description="Min seconds of inactivity for dormancy")
    min_multi_hop_depth: int = Field(2, ge=2, description="Min transaction hops for multi-hop path detection")
    max_multi_hop_depth: int = Field(4, ge=2, le=6, description="Max transaction hops for multi-hop path detection")
    min_peel_length: int = Field(2, ge=2, description="Min consecutive transactions to detect peeling-chain-like pattern")


class BehavioralDetectionResult(BaseModel):
    """Complete response containing detection summary and findings list."""
    dataset_id: str = Field(..., description="Target dataset ID")
    summary: BehaviorSummary = Field(..., description="Summary statistics")
    findings: List[BehavioralFinding] = Field(default_factory=list, description="List of structured findings")
